"""draw.io (mxfile) output validation helpers.

This module contains best-effort safety checks for both:
- deterministic outputs generated by this repo
- future AI-generated .drawio files

Keep it importable from app code (main/ai_reviewer) and reusable by scripts.
"""

from __future__ import annotations

import re
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path


@dataclass
class Issue:
    level: str  # ERROR | WARN
    message: str


_IMAGE_RE = re.compile(r"(?:^|;)image=([^;]+)")


def _localname(tag: str) -> str:
    if not tag:
        return tag
    if "}" in tag:
        return tag.split("}", 1)[1]
    return tag


def _extract_image_path(style: str) -> str | None:
    if not style:
        return None
    m = _IMAGE_RE.search(style)
    if not m:
        return None
    return m.group(1).strip()


def validate_drawio_xml(xml: str, *, require_azure2_icons: bool = False) -> list[Issue]:
    issues: list[Issue] = []

    try:
        root = ET.fromstring(xml)
    except ET.ParseError as e:
        return [Issue("ERROR", f"XML parse error: {e}")]

    root_tag = _localname(root.tag)
    if root_tag != "mxfile":
        issues.append(Issue("ERROR", f"Root element must be <mxfile>, got <{root.tag}>"))
        return issues

    cells = [e for e in root.iter() if _localname(getattr(e, "tag", "")) == "mxCell"]
    if not cells:
        issues.append(Issue("ERROR", "No <mxCell> elements found"))
        return issues

    ids: set[str] = set()
    dup: set[str] = set()
    azure2_image_count = 0

    for cell in cells:
        cid = cell.get("id")
        if not cid:
            issues.append(Issue("WARN", "Found <mxCell> without id"))
            continue
        if cid in ids:
            dup.add(cid)
        ids.add(cid)

        style = cell.get("style", "")

        # drawio-diagram-forge 互換: mxgraph.azure.* は VS Code / draw.io で欠けやすいので禁止
        # 期待する形式は image=img/lib/azure2/**/*.svg
        if "mxgraph.azure." in style.lower():
            issues.append(Issue("ERROR", "Forbidden shape style detected: mxgraph.azure.* (use img/lib/azure2 icons)"))

        img = _extract_image_path(style)
        if img:
            lower = img.lower()
            if lower.startswith("http://") or lower.startswith("https://"):
                issues.append(Issue("ERROR", f"Remote image URL is not allowed: {img}"))
            if require_azure2_icons and not lower.startswith("img/lib/azure2/"):
                issues.append(Issue("ERROR", f"Icon path must be under img/lib/azure2/: {img}"))
            if lower.startswith("img/lib/azure2/"):
                azure2_image_count += 1

    for cid in sorted(dup):
        issues.append(Issue("ERROR", f"Duplicate mxCell id: {cid}"))

    # Content validation: require at least one vertex (excluding the required root cells 0/1).
    # Blank diagrams often have only id=0 and id=1.
    vertex_cells = [c for c in cells if c.get("vertex") == "1" and (c.get("id") not in {"0", "1"})]
    if not vertex_cells:
        issues.append(Issue("ERROR", "No vertex nodes found (blank diagram)"))
        return issues

    if require_azure2_icons and azure2_image_count == 0:
        issues.append(Issue("ERROR", "No Azure2 icons found (expected image=img/lib/azure2/...)"))
        return issues

    edge_cells = [c for c in cells if c.get("edge") == "1"]
    for edge in edge_cells:
        src = edge.get("source")
        tgt = edge.get("target")
        if not src or not tgt:
            issues.append(Issue("WARN", f"Edge missing source/target (id={edge.get('id','?')})"))
            continue
        if src not in ids:
            issues.append(Issue("ERROR", f"Edge source id not found: {src}"))
        if tgt not in ids:
            issues.append(Issue("ERROR", f"Edge target id not found: {tgt}"))

    return issues


def validate_drawio(path: Path, *, require_azure2_icons: bool = False) -> list[Issue]:
    try:
        xml = path.read_text(encoding="utf-8")
    except OSError as e:
        return [Issue("ERROR", f"Failed to read file: {e}")]

    return validate_drawio_xml(xml, require_azure2_icons=require_azure2_icons)
