"""Validate draw.io (mxfile) output.

This script is intended to validate both:
- deterministic outputs generated by this repo
- future AI-generated .drawio files (best-effort safety checks)

Checks:
- XML parses and root is <mxfile>
- mxCell ids are unique
- edges refer to existing source/target ids
- image style paths do not point to remote URLs
- (optional) Azure icon paths are under img/lib/azure2/

Usage:
    uv run python ./scripts/validate_drawio.py path/to/diagram.drawio

Exit code:
  0 = OK
  1 = validation failed
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Allow importing from the app root (azure-ops-dashboard/)
_APP_ROOT = Path(__file__).resolve().parents[1]
if str(_APP_ROOT) not in sys.path:
    sys.path.insert(0, str(_APP_ROOT))

from drawio_validate import Issue, validate_drawio  # noqa: E402


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("path", type=Path, help="Path to .drawio file")
    parser.add_argument(
        "--require-azure2-icons",
        action="store_true",
        help="Fail if any mxCell image path is not under img/lib/azure2/",
    )
    args = parser.parse_args(argv)

    p: Path = args.path
    issues = validate_drawio(p, require_azure2_icons=args.require_azure2_icons)

    has_error = any(i.level == "ERROR" for i in issues)

    if not issues:
        print("OK: no issues found")
        return 0

    for i in issues:
        print(f"{i.level}: {i.message}")

    if has_error:
        print("FAILED")
        return 1

    print("OK (with warnings)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
